### ISSUE TITLE
macOS CI broken

### ISSUE THREAD

**Issue by praynaud** [Gfacco/json_to_quaff#7]
@Gfacco It seems your latest release does not pass the macOS CI and perhaps this is because of outdated actions...

I suggest switching to `fortran-lang/setup-fpm@v5` for pfm installation and also looking into `awvwgk/setup-fortran@v1` for gfortran installation, which allows you to bypass `msys2` on Windows.

Here is an example from the xLPR DLL refactoring project:

```yaml
name: Windows CI

on: [pull_request]

jobs:
  Win_Build_and_Test:
    runs-on: windows-latest

    steps:
    - name: Setup Fortran
      uses: awvwgk/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: gcc
        version: 12

    - name: Setup fpm
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check gfortran and fpm versions
      run: |
        gfortran --version
        fpm --version

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Build, test, create DLLs
      run: .\run_tests.bat
```
